# Generated by Django 2.1 on 2018-09-05 16:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180813_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('var1_value', models.IntegerField()),
                ('var2_value', models.IntegerField()),
                ('result_error', models.DecimalField(max_digits=10, decimal_places=3)),
                ('impr_pant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('view_class', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('preview_image', models.CharField(max_length=50)),
                ('var1_name', models.CharField(max_length=20)),
                ('var2_name', models.CharField(max_length=20)),
                ('var1_min', models.IntegerField()),
                ('var1_max', models.IntegerField()),
                ('var2_min', models.IntegerField()),
                ('var2_max', models.IntegerField()),
                ('goal', models.DecimalField(max_digits=5, decimal_places=2)),
                ('error_allowed', models.DecimalField(max_digits=5, decimal_places=4)),
                ('scale', models.IntegerField()),
                ('attempts_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_resolution', models.DateTimeField()),
                ('end_resolution', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Resoluter',
            fields=[
                ('resoluter_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='RESOLUTER_ID')),
                ('alias', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('education_level', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResoluterSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_cursor', models.IntegerField()),
                ('order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('resoluter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Resoluter')),
            ],
        ),
        migrations.CreateModel(
            name='ResoluterXSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('resoluter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Resoluter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.School')),
            ],
        ),
        migrations.CreateModel(
            name='ResoluterXUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=5)),
                ('facult', models.CharField(max_length=100)),
                ('resoluter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Resoluter')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.University')),
            ],
        ),
        migrations.AddField(
            model_name='problemresolution',
            name='resoluter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Resoluter'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ProblemResolution'),
        ),
    ]
