# Generated by Django 2.1 on 2018-09-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180905_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_audio', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='resoluter',
            name='resoluter_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='representation',
            name='resoluter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Resoluter'),
        ),
    ]
