# Generated by Django 2.1 on 2018-09-25 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180924_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('patterns', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
