# Generated by Django 2.1 on 2018-09-25 11:45

from django.db import migrations

def seed(apps, schema_editor):
	# Get reference of entity.	
	ClassTag = apps.get_model('tasks', 'ClassTag')
	# Make Tag R1
	r1 = ClassTag(
		name = 'R1',
		patterns = ['poco', 'poquito', 'mucho', 'más', 'menos', 'subir', 'bajar', 'quitar', 'agregar', 'poner', 'adicionar', 'restar', 'not a', 'not y', 'not para que']
	)
	r1.save()
	# Make Tag R2
	r2 = ClassTag(
		name = 'R2',
		patterns = ['poco', 'poquito', 'mucho', 'más', 'menos', 'subir', 'bajar', 'quitar', 'agregar', 'poner', 'adicionar', 'restar', 'mayor', 'menor', 'para que', 'not a', 'not y']
	)
	r2.save()
	# Make Tag R3
	r3 = ClassTag(
		name = 'R3',
		patterns = ['poco', 'poquito', 'mucho', 'más', 'menos', 'subir', 'bajar', 'quitar', 'agregar', 'poner', 'adicionar', 'restar', 'mayor', 'menor', 'para que', 'a', 'y']
	)
	r3.save()
	# Make Tag R4
	r4 = ClassTag(
		name = 'R4',
		patterns = ['poco', 'poquito', 'mucho', 'más', 'menos', 'subir', 'bajar', 'quitar', 'agregar', 'poner', 'adicionar', 'restar', 'mayor', 'menor', 'duplicar', 'triplicar', 'cuadrupilcar', 'para que', 'a', 'y']
	)
	r4.save()
	# Make Tag R5
	r5 = ClassTag(
		name = 'R5',
		patterns = ['poco', 'poquito', 'mucho', 'más', 'menos', 'subir', 'bajar', 'quitar', 'agregar', 'poner', 'adicionar', 'restar', 'mayor', 'menor', 'duplicar', 'triplicar', 'cuadrupilcar', 'tercera parte', 'cuarta parte', 'quinta parte', 'entre la mitad de', 'para que', 'a', 'y']
	)
	r5.save()
	
class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_classtag'),
    ]

    operations = [
    	migrations.RunPython(seed),
    ]
