# Generated by Django 5.1.2 on 2024-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_contactobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtag',
            name='patterns',
            field=models.CharField(blank=True, default=[], max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolutersession',
            name='order',
            field=models.TextField(blank=True),
        ),
    ]
